# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: acts.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'acts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nacts.proto\x12\tacts.grpc\"Z\n\x0eMessageOptions\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03tag\x18\x04 \x01(\t\x12\x0b\n\x03key\x18\x05 \x01(\t\"Z\n\x07Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\t\x12\x10\n\x03\x61\x63k\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x04 \x01(\x0cH\x01\x88\x01\x01\x42\x06\n\x04_ackB\x07\n\x05_data2\x7f\n\x0b\x41\x63tsService\x12\x30\n\x04Send\x12\x12.acts.grpc.Message\x1a\x12.acts.grpc.Message\"\x00\x12>\n\tOnMessage\x12\x19.acts.grpc.MessageOptions\x1a\x12.acts.grpc.Message\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEOPTIONS']._serialized_start=25
  _globals['_MESSAGEOPTIONS']._serialized_end=115
  _globals['_MESSAGE']._serialized_start=117
  _globals['_MESSAGE']._serialized_end=207
  _globals['_ACTSSERVICE']._serialized_start=209
  _globals['_ACTSSERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
