# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import acts_channel.proto.acts_pb2 as acts__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in acts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActsServiceStub(object):
    """acts service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/acts.grpc.ActsService/Send',
                request_serializer=acts__pb2.Message.SerializeToString,
                response_deserializer=acts__pb2.Message.FromString,
                _registered_method=True)
        self.OnMessage = channel.unary_stream(
                '/acts.grpc.ActsService/OnMessage',
                request_serializer=acts__pb2.MessageOptions.SerializeToString,
                response_deserializer=acts__pb2.Message.FromString,
                _registered_method=True)


class ActsServiceServicer(object):
    """acts service
    """

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnMessage(self, request, context):
        """rpc OnFlow(Message) returns (stream Message) {}
        rpc OnStep(Message) returns (stream Message) {}
        rpc OnAct(Message) returns (stream Message) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=acts__pb2.Message.FromString,
                    response_serializer=acts__pb2.Message.SerializeToString,
            ),
            'OnMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.OnMessage,
                    request_deserializer=acts__pb2.MessageOptions.FromString,
                    response_serializer=acts__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acts.grpc.ActsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('acts.grpc.ActsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActsService(object):
    """acts service
    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acts.grpc.ActsService/Send',
            acts__pb2.Message.SerializeToString,
            acts__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/acts.grpc.ActsService/OnMessage',
            acts__pb2.MessageOptions.SerializeToString,
            acts__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
